// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportFile(arg1, arg2) {
  return window['go']['main']['App']['ExportFile'](arg1, arg2);
}

export function GetStartupFile() {
  return window['go']['main']['App']['GetStartupFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
