// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportFile(arg1:string,arg2:string):Promise<void>;

export function GetPid():Promise<number>;

export function GetStartupFile():Promise<string>;

export function GetWindows():Promise<Array<Record<string, any>>>;

export function OpenFile():Promise<Record<string, any>>;

export function OpenInNewWindow(arg1:string,arg2:string):Promise<void>;

export function OpenPath(arg1:string):Promise<Record<string, any>>;

export function RegisterWindow(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function SendTabToWindow(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UnregisterWindow():Promise<void>;
