// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportFile(arg1:string,arg2:string):Promise<void>;

export function GetStartupFile():Promise<string>;

export function OpenFile():Promise<Record<string, any>>;

export function OpenPath(arg1:string):Promise<Record<string, any>>;

export function SaveFile(arg1:string,arg2:string):Promise<Record<string, any>>;
